In [120]:
import numpy as np


# Arrays

## NumPy - Create Array

In [121]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [122]:
type(a)

numpy.ndarray

In [123]:
a.dtype

dtype('int64')

In [124]:
a.ndim

1

In [125]:
a.shape

(3,)

In [126]:
b = np.array([1.2, 3.5, 5])
b

array([1.2, 3.5, 5. ])

In [127]:
b.dtype

dtype('float64')

In [128]:
b = np.array([(1,2,3), (4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
b.shape

(2, 3)

In [130]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [131]:
np.ones((2,3), dtype='int32') 

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [132]:
np.arange( 10 )

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
np.arange( 10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [134]:
np.arange( 10, 20, 3 )

array([10, 13, 16, 19])

In [135]:
a=np.arange( 10 )
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
a.shape

(10,)

In [137]:
b=a.reshape(2,5)

In [138]:
b.shape

(2, 5)

In [139]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Basic Operations ##

In [140]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [141]:
a+b


array([20, 31, 42, 53])

In [142]:
a-b

array([20, 29, 38, 47])

In [143]:
a * b

array([  0,  30,  80, 150])

In [144]:
b*2

array([0, 2, 4, 6])

In [145]:
b**2

array([0, 1, 4, 9])

In [146]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [147]:
a

array([20, 30, 40, 50])

In [148]:
a>35

array([False, False,  True,  True])

In [149]:
a[[False, False,  True,  True]]

array([40, 50])

In [150]:
a[a>35]

array([40, 50])

In [151]:
a % 3 

array([2, 0, 1, 2])

In [152]:
a % 3 == 0

array([False,  True, False, False])

In [153]:
a[a % 3 == 0]

array([30])

## Indexing & Slicing

In [154]:
a = np.arange(10)**3
a


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [155]:
a[2]

8

In [156]:
a[2:5:2]

array([ 8, 64])

In [157]:
a[2]=100
a

array([  0,   1, 100,  27,  64, 125, 216, 343, 512, 729])

In [158]:
a[:6:2] = -1000 
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [159]:
a[[ True,  False,  False,  False,  False, False, False, False, False,True]]

array([-1000,   729])

In [160]:
a < 100

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [161]:
a[a < 100]

array([-1000,     1, -1000,    27, -1000])

In [162]:
b = np.array([(1,2,3), (4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
np.mean(b)

3.5

In [164]:
np.mean(b, axis=0)

array([2.5, 3.5, 4.5])

In [165]:
np.mean(b, axis=1)

array([2., 5.])

In [166]:
b.shape

(2, 3)

In [167]:
b[1][2]

6

In [168]:
b[1,2]

6

In [169]:
b[0,1]=10

In [170]:
b

array([[ 1, 10,  3],
       [ 4,  5,  6]])

In [171]:
b[0]

array([ 1, 10,  3])

In [172]:
b[0, 1:]

array([10,  3])

In [173]:
b[:, 1]

array([10,  5])

In [174]:
b.T

array([[ 1,  4],
       [10,  5],
       [ 3,  6]])

In [175]:
a = np.arange(24).reshape(2, 3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [176]:
a.shape

(2, 3, 4)

In [177]:
a[1,1,0]

16

In [178]:
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [179]:
a[[0,1,2,3],[1,2,3,4]]

array([ 1,  8, 15, 22])

In [180]:
(a % 3 == 0)

array([[ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False]])

In [181]:
a[np.array([[ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False],
       [ True, False, False,  True, False, False]])]

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [182]:
a[(a % 3 == 0)]

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [183]:
(a % 3 == 0) * a

array([[ 0,  0,  0,  3,  0,  0],
       [ 6,  0,  0,  9,  0,  0],
       [12,  0,  0, 15,  0,  0],
       [18,  0,  0, 21,  0,  0]])

In [184]:
a=np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [185]:
a[4]

array([20, 21, 22, 23, 24])

In [186]:
a[:,2]

array([ 2,  7, 12, 17, 22])

In [187]:
a[:,1:4:2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [188]:
a[1:4:2,0:3:2]

array([[ 5,  7],
       [15, 17]])

## Functions/Methods - Examples ##

In [189]:
A = np.arange(5)
A

array([0, 1, 2, 3, 4])

In [190]:
np.sum(A)

10

In [191]:
A.sum()

10

In [192]:
np.prod(A)

0

In [193]:
np.all(A)

False

In [194]:
np.any(A)

True

In [195]:
np.count_nonzero(A)

4

In [196]:
np.sqrt(A)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [197]:
np.diff(A)

array([1, 1, 1, 1])

In [198]:
np.cumsum(A)

array([ 0,  1,  3,  6, 10])

In [199]:
np.cumprod(A)

array([0, 0, 0, 0, 0])

In [200]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [201]:
np.char.upper(names)

array(['BOB', 'JOE', 'WILL', 'BOB', 'WILL', 'JOE', 'JOE'], dtype='<U4')

In [202]:
np.char.count(names, "il")

array([0, 0, 1, 0, 1, 0, 0])

In [203]:
np.char.startswith(names, "B")

array([ True, False, False,  True, False, False, False])

In [204]:
np.char.find(names, "l")

array([-1, -1,  2, -1,  2, -1, -1])

 ## List vs Array ##

In [205]:
list1=list(range(4))
list2=list(range(4,8))
print(list1)
print(list2)

[0, 1, 2, 3]
[4, 5, 6, 7]


In [206]:
list1 + list2

[0, 1, 2, 3, 4, 5, 6, 7]

In [207]:
result=[]
for i,j in zip(list1,list2):
    result.append(i+j)
result

[4, 6, 8, 10]

In [208]:
array1=np.arange(4)
array2=np.arange(4,8)
print(array1)
print(array2)

[0 1 2 3]
[4 5 6 7]


In [209]:
array1 + array2

array([ 4,  6,  8, 10])

In [210]:
array3=np.arange(5)
array1 + array3

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [211]:
a_list=list(range(1000000))
an_array=np.arange(1000000)

In [212]:
%timeit sum(a_list)

4.8 ms ± 21.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [213]:
%timeit np.sum(an_array)

387 µs ± 1.52 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [214]:
an_array.size

1000000

In [215]:
an_array.nbytes

8000000

In [216]:
#size of list - pointers
import sys
print(sys.getsizeof(a_list))

8000056


In [90]:
#size of each list element
print(sys.getsizeof(a_list[10000]))

28
